### ISSUE TITLE
radoneye list 

### ISSUE THREAD

**Issue by Ndolam** [sormy/radoneye#2]
I installed radoneye with
  pip3 install radoneye
and after putting ~/.local/bin at the beginning of my PATH, I can run 
  radoneye --help
but when I run 
  radoneye list  
I get this:

```
Traceback (most recent call last):
  File "/home/myhomedir/.local/bin//radoneye", line 8, in <module>
    sys.exit(main())
  File "/home/myhomedir/.local/lib/python3.9/site-packages/radoneye/__main__.py", line 8, in main
    asyncio.run(cli_main(sys.argv))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/myhomedir/.local/lib/python3.9/site-packages/radoneye/cli.py", line 313, in main
    await args.func(args)
  File "/home/myhomedir/.local/lib/python3.9/site-packages/radoneye/cli.py", line 30, in cmd_list
    for dev in await RadonEyeScanner.discover(adapter=args.adapter, timeout=args.timeout)
  File "/home/myhomedir/.local/lib/python3.9/site-packages/radoneye/scanner.py", line 16, in discover
    devices = await BleakScanner.discover(timeout=timeout, adapter=adapter)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/bleak/__init__.py", line 317, in discover
    async with cls(**kwargs) as scanner:
  File "/usr/local/lib/python3.9/site-packages/bleak/__init__.py", line 158, in __aenter__
    await self._backend.start()
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/scanner.py", line 168, in start
    manager = await get_global_bluez_manager()
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/manager.py", line 1046, in get_global_bluez_manager
    await instance.async_init()
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/manager.py", line 278, in async_init
    assert_reply(reply)
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.AccessDenied] Rejected send message, 2 matched rules; type="method_call", sender=":1.4981" (uid=1000 pid=15169 comm="/usr/local/bin/python3.9 /home/myhomedir/.local/bin//rad") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.bluez" (uid=0 pid=1691 comm="/usr/lib/bluetooth/bluetoothd ")
```

I'm no python expert... any idea on what I am doing wrong?

Thanks.

**Comment by sormy** [comment]
Looks like “access denied”, user doesn’t have access to dbus or bluetooth.

**Comment by Ndolam** [comment]
Sormy, thanks very much for the response.
Running as root I am able to use radoneye to read data from my (old version) RD200.

Having said that... the program I use to do that ("RadonEye RD200 Reader (Bluetooth/BLE)", V 0.1c, by Carlos Andre) is able to read the data when executed by me.  Can you offer me any insight as to why I can use that one as me, but I have to use yours as root?  (Not only am I not a Python expert, I am the furthest thing from a bluetooth expert, so I am confused about why one Python program can get my RD200 data via bluetooth, but another one can't.)

Cheers.

**Comment by sormy** [comment]
The library used for bluetooth in my repo is bleak. It seems like it needs access to dbus and bluetooth. Im not sure about other library. It is not required to run it as root if you have needed permissions granted to user. Check this https://unix.stackexchange.com/questions/348441/how-to-allow-non-root-systemd-service-to-use-dbus-for-ble-operation

**Comment by Ndolam** [comment]
Thanks very much for pointing me to that article.
I am not able to run that program as my ordinary user.

Interestng, sometimes after running your program, the one I refer to above comes up with some wild radon reading (in the millions).
